server:
  port: 6001

spring:
  application:
    name: appgateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        - id: appsecurity
          uri: http://localhost:81
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=1

        - id: appinvoice
          uri: http://localhost:82
          predicates:
            - Path=/invoice/**
          filters:
            - StripPrefix=1
            # - JwtAuthenticationFilter

# OK
        - id: apppay
          uri: http://localhost:83
          predicates:
            - Path=/api/pay/**
          filters:
            # - StripPrefix=1
            # - JwtAuthenticationFilter

        - id: apptransaction
          uri: http://localhost:84
          predicates:
            - Path=/api/transaction/**
          filters:
            - StripPrefix=1
            # - JwtAuthenticationFilter